version: '3'

services:
  app:
    container_name: 'us-urp-app'
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  db:
    container_name: 'us-urp-db'
    image: postgres:14.3
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data


volumes:
  dbdata: